#!/bin/bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

# Exit immediately if a command exits with a non-zero status
set -e

echo "==> Setting application back to initial state..."

# Ionic
rm -rf \
    node_modules/ \
    www/ \

# iOS
rm -rf \
    ios/App/Pods \
    ios/App/public \
    ios/App/Podfile.lock \
    ios/capacitor-cordova-ios-plugins/ \

# Android
rm -rf \
    android/app/build \
    android/capacitor-cordova-android-plugins \

# Electron
rm -rf \
    electron/app \
    electron/node_modules \
    
echo "==> Setup complete."
