#!/bin/bash

# script/update: Update application to run for its current checkout.

# Exit immediately if a command exits with a non-zero status
set -e

# Store a local variable of the scripts current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

${DIR}/bootstrap

echo "==> Updating NPM dependencies..."
npm update

echo "==> Updating Angular dependencies..."
ng update

echo "echo ==> Dependency updates complete."
